### ISSUE TITLE
Boxes are on the left

### ISSUE THREAD

**Issue by CyberGamer78** [CyberGamer78/competition#1]
Whenever I open the project in different screen sizes the boxes under trending sections are always on the right I want it to be in the center, also in this project only html and css can be used no JavaScript

**Comment by saprameya** [comment]
Hi, I'd like to offer a solution to this.

**Comment by CyberGamer78** [comment]
> Hi, I'd like to offer a solution to this.
Ok sure I have assigned the issue, I request you to please reply me sooner because I want this file before 10th, also I have updated the css file so you should update your files too, thank you for you support

**Comment by CyberGamer78** [comment]
> Hi, I'd like to offer a solution to this.
I saw your code, Thank you for you contribution, I know I should not ask for more favours but can you also do something about the header the "Home Information Contact Us etc" buttons shows black section if open the website in phone

**Comment by saprameya** [comment]
I will look into it
